---
title: "check_answer_plots"
author: "Brooke Sevchik"
date: "6/14/2023"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

```{r data manipulation, check answer plot}
avg_check_answer_acc_df_list
```

```{r data manipulation & plot, check answer plot 1}
#iterate through data frame for each subject
for (subject in unique_subjects) {
  #get data frame for current subject
  subject_df <- avg_check_answer_acc_df_list[[subject]]
  #make the plot for current subject
   plot <- ggplot(subject_df) +
    geom_line(aes(x = trialCount, y = threat, color = "Threat")) +
    geom_line(aes(x = trialCount, y = neutral, color = "Neutral")) +
    geom_point(aes(x = trialCount, y = threat, color = "Threat")) +
    geom_point(aes(x = trialCount, y = neutral, color = "Neutral")) +
    labs(title = paste("Subject:", subject), x = "Trial", y = "Accuracy (%)") +
    scale_color_manual(values = c(Threat = "red", Neutral = "blue"))
  #print plot for subject
  print(plot)
}
```

```{r data manipulation & plot, check answer plot 1 w STAI scores included}
#iterate through data frame for each subject
for (subject in unique_subjects) {
  #get data frame for current subject
  subject_df <- avg_check_answer_acc_df_list[[subject]]
  anxiety_level <- df_pilot1_STAI_simple[df_pilot1_STAI_simple$subject == subject, "anxiety_level"]
  anxiety_level_value <- anxiety_level[1]

  #make the plot for current subject
   plot <- ggplot(subject_df) +
    geom_line(aes(x = trialCount, y = threat, color = "Threat")) +
    geom_line(aes(x = trialCount, y = neutral, color = "Neutral")) +
    geom_point(aes(x = trialCount, y = threat, color = "Threat")) +
    geom_point(aes(x = trialCount, y = neutral, color = "Neutral")) +
    labs(title = paste("Subject:", subject, anxiety_level_value), x = "Trial", y = "Accuracy (%)") +
    scale_color_manual(values = c(Threat = "red", Neutral = "blue"))
  #print plot for subject
  print(plot)
}
```



#ACROSS SUBJECTS

```{r data manipulation, check answer plot across subjects}
average_across_df
```

```{r plot, check answer plot across subjects}
ggplot(average_across_df) +
  geom_line(aes(x = trial, y = threat, color = "Threat")) +
  geom_line(aes(x = trial, y = neutral, color = "Neutral")) + 
  geom_point(aes(x = trial, y = threat, color = "Threat")) +
  geom_point(aes(x = trial, y = neutral, color = "Neutral")) +
  labs(title = "Average Across Subjects", x = "Trial", y = "Accuracy (%)") +
  scale_color_manual(values = c(Threat = "red", Neutral = "blue"))
```

```{r plot, check answer plot across subjects}
ggplot(avg_across_low_anxiety_df) +
  geom_line(aes(x = trial, y = threat, color = "Threat")) +
  geom_line(aes(x = trial, y = neutral, color = "Neutral")) + 
  geom_point(aes(x = trial, y = threat, color = "Threat")) +
  geom_point(aes(x = trial, y = neutral, color = "Neutral")) +
  labs(title = "Average Across Subjects with Low Trait Anxiety", x = "Trial", y = "Accuracy (%)") +
  scale_color_manual(values = c(Threat = "red", Neutral = "blue"))

ggplot(avg_across_moderate_anxiety_df) +
  geom_line(aes(x = trial, y = threat, color = "Threat")) +
  geom_line(aes(x = trial, y = neutral, color = "Neutral")) + 
  geom_point(aes(x = trial, y = threat, color = "Threat")) +
  geom_point(aes(x = trial, y = neutral, color = "Neutral")) +
  labs(title = "Average Across Subjects with Moderate Trait Anxiety", x = "Trial", y = "Accuracy (%)") +
  scale_color_manual(values = c(Threat = "red", Neutral = "blue"))

ggplot(avg_across_high_anxiety_df) +
  geom_line(aes(x = trial, y = threat, color = "Threat")) +
  geom_line(aes(x = trial, y = neutral, color = "Neutral")) + 
  geom_point(aes(x = trial, y = threat, color = "Threat")) +
  geom_point(aes(x = trial, y = neutral, color = "Neutral")) +
  labs(title = "Average Across Subjects with High Trait Anxiety", x = "Trial", y = "Accuracy (%)") +
  scale_color_manual(values = c(Threat = "red", Neutral = "blue"))
```







