---
title: "check_answer_event_plots_2"
author: "Brooke Sevchik"
date: "6/16/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

```{r data manipulation, check answer plot}
check_answer_percent_first_df

#manipulate the data frame
check_answer_percent_plot_df <- check_answer_percent_first_df %>%
  pivot_longer(cols = c(percent_threat, percent_neutral, percent_equal),
               names_to = "threat_status",
               values_to = "percentage")
check_answer_percent_plot_df

#rename threat status values such that they no longer are called percent_
check_answer_percent_plot_df$threat_status <- factor(check_answer_percent_plot_df$threat_status,
                                                 levels = c("percent_threat", "percent_neutral", "percent_equal"),
                                                 labels = c("threat", "neutral", "equal"))
check_answer_percent_plot_df

#group by subject and threat_status, summarize the percentage
check_answer_percent_summary <- check_answer_percent_plot_df %>%
  group_by(subject, threat_status) %>%
  summarize(percentage = mean(percentage))

check_answer_percent_summary
```

```{r data manipulation & plot, Check Answer Plot_2 1}
ggplot(data = check_answer_percent_summary, mapping = aes(x = threat_status, y = percentage, fill = threat_status )) +
  geom_boxplot(alpha = 0.5, outlier.shape = NA) +
  geom_jitter(width=0.1, height = 0.0) +
  labs(fill = "Threat Status", x = "Threat Status", y = "Percentage")+
  theme(legend.position = "none")
```

#include STAI

```{r data manipulation, Check Answer Plot_2 1 Anxiety}
check_answer_percent_summary
df_pilot1_STAI_simple

#merge data frames
check_answer_percent_summary_STAI <- merge(df_pilot1_STAI_simple, check_answer_percent_summary, by = "subject")
check_answer_percent_summary_STAI
```
```{r data manipulation & plot, Check Answer Plot_2 1 Anxiety 2}

#high anxiety data frame, check answer 2 first plot
high_anxiety_check_answer_summary <- check_answer_percent_summary_STAI %>%
  filter(anxiety_level == 'high trait anxiety')
high_anxiety_check_answer_summary

#moderate anxiety data frame, check answer 2 first plot
moderate_anxiety_check_answer_summary <- check_answer_percent_summary_STAI %>%
  filter(anxiety_level == 'moderate trait anxiety')
moderate_anxiety_check_answer_summary

#low anxiety data frame, check answer 2 first plot
low_anxiety_check_answer_summary <- check_answer_percent_summary_STAI %>%
  filter(anxiety_level == 'low trait anxiety')
low_anxiety_check_answer_summary

```
```{r data manipulation & plot, Check Answer Plot_2 1 Anxiety 3}
#high anxiety plot, check answer 2 plot1
ggplot(data = high_anxiety_check_answer_summary, mapping = aes(x = threat_status, y = percentage, fill = threat_status)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1, height = 0.0) +
  labs(title = "Plot 1 Check Answer 2, High Anxiety", fill = "Threat Status", x = "Threat Status", y = "Percentage")

#moderate anxiety plot, check answer 2 plot1
ggplot(data = moderate_anxiety_check_answer_summary, mapping = aes(x = threat_status, y = percentage, fill = threat_status)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1, height = 0.0) +
  labs(title = "Plot 1 Check Answer 2, Moderate Anxiety", fill = "Threat Status", x = "Threat Status", y = "Percentage")

#low anxiety plot, check answer 2 plot1
ggplot(data = low_anxiety_check_answer_summary, mapping = aes(x = threat_status, y = percentage, fill = threat_status)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1, height = 0.0) +
  labs(title = "Plot1 Check Answer 2, Low Anxiety", fill = "Threat Status", x = "Threat Status", y = "Percentage")
```



#separate plot, just filtering the first trial

```{r data manipulation, Check Answer Plot_2 2}
check_answer_percent_first_df_trial1

#manipulate the data frame
check_answer_percent_first_df_trial1_plot <- check_answer_percent_first_df_trial1 %>%
  pivot_longer(cols = c(percent_threat, percent_neutral, percent_equal),
               names_to = "threat_status",
               values_to = "percentage")

#rename threat status values such that they no longer are called percent_
check_answer_percent_first_df_trial1_plot$threat_status <- factor(check_answer_percent_first_df_trial1_plot$threat_status,
                                                 levels = c("percent_threat", "percent_neutral", "percent_equal"),
                                                 labels = c("threat", "neutral", "equal"))

#group by threat_status, summarize the percentage
check_answer_percent_summary_trial1 <- check_answer_percent_first_df_trial1_plot %>%
  group_by(threat_status) %>%
  summarize(percentage = mean(percentage))

check_answer_percent_summary_trial1
```



```{r Check Answer Plot_2 2, echo=FALSE}
#this is the plot for JUST looking at the first trial. Across subjects, decide which
ggplot(data = check_answer_percent_summary_trial1, mapping = aes(x = threat_status, y = percentage)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "Threat Status", y = "Percentage", title = "% of Subjects that got Threat or Neutral Images correct first on the first trial") +
  scale_x_discrete(labels = c("threat", "neutral", "equal")) 
```


##including STAI scores


```{r data manipulation, Check Answer Plot_2 2 Anxiety 3}

#initialize empty list
check_answer_percent_summary_list <- list()

#iterate through data frames
for (df_name in c("check_answer_percent_first_df_low", "check_answer_percent_first_df_moderate", "check_answer_percent_first_df_high")) {
  df <- get(df_name)
  
  #manipulate data frame to get in desired format
  df_plot <- df %>%
    pivot_longer(cols = c(percent_threat, percent_neutral, percent_equal),
                 names_to = "threat_status",
                 values_to = "percentage")
  #rename threat status values
  df_plot$threat_status <- factor(df_plot$threat_status,
                                  levels = c("percent_threat", "percent_neutral", "percent_equal"),
                                  labels = c("threat", "neutral", "equal"))
  
  #group by threat_status, get average percentage
  df_summary <- df_plot %>%
    group_by(threat_status) %>%
    summarize(percentage = mean(percentage))
  
  #add current data frame to the list
  check_answer_percent_summary_list[[df_name]] <- df_summary
}

#how to access resulting data frames from the list
check_answer_percent_summary_low <- check_answer_percent_summary_list$check_answer_percent_first_df_low
check_answer_percent_summary_moderate <- check_answer_percent_summary_list$check_answer_percent_first_df_moderate
check_answer_percent_summary_high <- check_answer_percent_summary_list$check_answer_percent_first_df_high

check_answer_percent_summary_low
check_answer_percent_summary_moderate
check_answer_percent_summary_high

```

```{r Check Answer Plot_2 2 Anxiety, echo=FALSE}
#these are the plots for JUST looking at the first trial

#low anxiety
ggplot(data = check_answer_percent_summary_low, mapping = aes(x = threat_status, y = percentage)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "Threat Status", y = "Percentage", title = " % of Low Anxiety Subjects that got Threat or Neutral Images correct first on trial 1") +
  scale_x_discrete(labels = c("threat", "neutral", "equal")) 


#moderate anxiety
ggplot(data = check_answer_percent_summary_moderate, mapping = aes(x = threat_status, y = percentage)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "Threat Status", y = "Percentage", title = "% of Moderate Anxiety subjects that got threat or neutral images correct first on trial 1") +
  scale_x_discrete(labels = c("threat", "neutral", "equal")) 

#high anxiety
ggplot(data = check_answer_percent_summary_high, mapping = aes(x = threat_status, y = percentage)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "Threat Status", y = "Percentage", title = "% of High Anxiety subjects that got threat or neutral images correct first on trial 1") +
  scale_x_discrete(labels = c("threat", "neutral", "equal")) 

```

















