---
title: "drop_event_plots_Anxiety_CM"
author: "Brooke Sevchik"
date: "6/12/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

```{r data manipulation, drop event plot}
percentage_drop_plot_df
```
```{r data manipulation, drop event plot including accuracy requirement}
percentage_drop_plot_acc_df
```




```{r drop_event_plot by subject, echo=FALSE}
ggplot(data = percentage_drop_plot_df, mapping = aes(x = threat_status, y = percentage, fill = threat_status)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1) +
  geom_hline(yintercept = 40, linetype = "dotted", color = "blue") +
  geom_hline(yintercept = 60, linetype = "dotted", color = "red")+
  labs(fill = "Threat Status", x = "Threat Status", y = "Percentage", title = "% that Subject Selected Threat vs. Neutral Images on Their First Drag and Drop")
#change labels at some point to reflect that here, "threat_status" refers to which type of image the participant selected first to drag & drop, and "percentage" refers to the percent, for each subject, that out of how many trials it took them to complete the task, on the first attempt the first image they chose to drag & drop was a threat versus a neutral image
#added the dotted lines here to indicate percent if it was by chance - so 60% for neutral (red dotted line), 40% for threat (blue dotted line)
```


```{r drop_event_plot by subject INCLUDING ACCURACY, echo=FALSE}
ggplot(data = percentage_drop_plot_acc_df, mapping = aes(x = threat_status, y = percentage, fill = threat_status)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1) +
  geom_hline(yintercept = 40, linetype = "dotted", color = "blue") +
  geom_hline(yintercept = 60, linetype = "dotted", color = "red") +
  labs(fill = "Threat Status", x = "Threat Status", y = "percentage", title = "% Subject Selected Threat vs. Neutral Image on First ACCURATE Drag & Drop")
#change labels at some point to reflect that here, "threat_status" refers to which type of image the participant selected first to drag & drop, and "percentage" refers to the percent, for each subject, that out of how many trials it took them to complete the task, on the first attempt the first image they chose to drag & drop was a threat versus a neutral image
#added the dotted lines here to indicate percent if it was by chance - so 60% for neutral (red dotted line), 40% for threat (blue dotted line)
```

#Including STAI scores/anxiety levels


```{r drop_event_plot by subject Anxiety, echo=FALSE}
#high anxiety plot
ggplot(data = percentage_drop_plot_high_anxiety, mapping = aes(x = threat_status, y = percentage, fill = threat_status)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1) +
  geom_hline(yintercept = 40, linetype = "dotted", color = "blue") +
  geom_hline(yintercept = 60, linetype = "dotted", color = "red")+
  labs(fill = "Threat Status", x = "Threat Status", y = "Percentage", title = "% High Anxiety Subject Selected Threat vs. Neutral Images on First Drag and Drop")

#moderate anxiety plot
ggplot(data = percentage_drop_plot_moderate_anxiety, mapping = aes(x = threat_status, y = percentage, fill = threat_status)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1) +
  geom_hline(yintercept = 40, linetype = "dotted", color = "blue") +
  geom_hline(yintercept = 60, linetype = "dotted", color = "red")+
  labs(fill = "Threat Status", x = "Threat Status", y = "Percentage", title = "% Moderate Anxiety Subject Selected Threat vs. Neutral Images on First Drag and Drop")

#low anxiety plot
ggplot(data = percentage_drop_plot_low_anxiety, mapping = aes(x = threat_status, y = percentage, fill = threat_status)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1) +
  geom_hline(yintercept = 40, linetype = "dotted", color = "blue") +
  geom_hline(yintercept = 60, linetype = "dotted", color = "red")+
  labs(fill = "Threat Status", x = "Threat Status", y = "Percentage", title = "% Low Anxiety Subject Selected Threat vs. Neutral Images on First Drag and Drop")
```


```{r drop_event_plot by subject INCLUDING ACCURACY, echo=FALSE}
#high anxiety plot
ggplot(data = percentage_drop_plot_high_anxiety_acc, mapping = aes(x = threat_status, y = percentage, fill = threat_status)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1) +
  geom_hline(yintercept = 40, linetype = "dotted", color = "blue") +
  geom_hline(yintercept = 60, linetype = "dotted", color = "red") +
  labs(fill = "Threat Status", x = "Threat Status", y = "percentage", title = "% High Anxiety Subject Selected Threat vs. Neutral Image on 1st ACCURATE Drop")

#moderate anxiety plot
ggplot(data = percentage_drop_plot_moderate_anxiety_acc, mapping = aes(x = threat_status, y = percentage, fill = threat_status)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1) +
  geom_hline(yintercept = 40, linetype = "dotted", color = "blue") +
  geom_hline(yintercept = 60, linetype = "dotted", color = "red") +
  labs(fill = "Threat Status", x = "Threat Status", y = "percentage", title = "% Moderate Anxiety Subject Selected Threat vs. Neutral Image on 1st ACCURATE Drop")

#low anxiety plot
ggplot(data = percentage_drop_plot_low_anxiety_acc, mapping = aes(x = threat_status, y = percentage, fill = threat_status)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1) +
  geom_hline(yintercept = 40, linetype = "dotted", color = "blue") +
  geom_hline(yintercept = 60, linetype = "dotted", color = "red") +
  labs(fill = "Threat Status", x = "Threat Status", y = "percentage", title = "% Low Anxiety Subject Selected Threat vs. Neutral Image on 1st ACCURATE Drop")

```


