---
title: "OOO_plots_Anxiety_CM"
author: "Brooke Sevchik"
date: "3/5/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```


## FIRST PLOTS

```{r data manipulation, OOO Plot 1.1}
#Percentage that participants, out of trials when they were inaccurate and the other inaccurate option was a different threat type, chose threat vs. neutral incorrect images
threat_percent_ooo_df <- mistake_df %>%
  count(chosenThreatStatus) %>%
  mutate(total_observations = nrow(mistake_df)) %>%
  mutate(percentage_chosenThreatStatus = (n/total_observations)*100)
threat_percent_ooo_df
```
```{r OOO Plot 1.1, echo=FALSE}
#Percentage that participants, out of trials when they were inaccurate and the other inaccurate option was a different threat type, chose threat vs. neutral incorrect images
ggplot(data = threat_percent_ooo_df, mapping = aes(x = chosenThreatStatus, y = percentage_chosenThreatStatus)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "Chosen Threat Status", y = "Percentage", title = "% Participants Chose Threat vs. Neutral Inaccurate Images in Odd One Out Task") +
  scale_x_discrete(labels = c("neutral", "threat")) 
```


```{r data manipulation, OOO Plot 1.2}
threat_percent_subjects_df <- mistake_df %>%
  group_by(subject) %>% 
  count(chosenThreatStatus) %>%
  mutate(total_observations = nrow(mistake_df)) %>%
  mutate(percentage_chosenThreatStatus = (n/total_observations)*100)
threat_percent_subjects_df
```


#by subject

```{r OOO Plot 1.2, echo=FALSE}
ggplot(data = threat_percent_subjects_df, mapping = aes(x = chosenThreatStatus, y = percentage_chosenThreatStatus, fill = chosenThreatStatus)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1) +
  labs(title = "% Each Subject Chose Threat vs. Neutral Inaccurate Images in Odd One Out Task", x = "Chosen Threat Status", y = "Percentage")
```



##SECOND PLOT

```{r data manipulation, OOO Plot 2.1}
subject_acc_ooo_df <- ooo_df %>%
  group_by(subject, chosenThreatStatus) %>%
  summarize(mean_acc = mean(acc))
subject_acc_ooo_df
```



```{r OOO Plot 2.1, echo=FALSE}
ggplot(subject_acc_ooo_df, aes(x = chosenThreatStatus, y = mean_acc, fill=chosenThreatStatus)) +
  geom_boxplot(alpha=0.5) +
  geom_jitter(width=0.1) +
  labs(title = "Mean Accuracy by Subject in Odd One Out Task by Chosen Threat Status", x = "Chosen Threat Status", y = "Mean Accuracy")
```

#PLOTS WITH STAI SCORES ADDED

```{r data manipulation, OOO Plot 1.2 Anxiety}
ooo_anxiety_df
threat_percent_anxiety_df <- ooo_anxiety_df  %>%
  group_by(subject, anxiety_level) %>% 
  count(chosenThreatStatus) %>%
  mutate(total_observations = nrow(mistake_df)) %>%
  mutate(percentage_chosenThreatStatus = (n/total_observations)*100)
threat_percent_anxiety_df

#high anxiety data frame, ooo first plot
high_anxiety_threat_df <- threat_percent_anxiety_df %>%
  filter(anxiety_level == 'high trait anxiety')
high_anxiety_threat_df

#moderate anxiety data frame, ooo first plot
moderate_anxiety_threat_df <- threat_percent_anxiety_df %>%
  filter(anxiety_level == 'moderate trait anxiety')
moderate_anxiety_threat_df

#high anxiety data frame, ooo first plot
low_anxiety_threat_df <- threat_percent_anxiety_df %>%
  filter(anxiety_level == 'low trait anxiety')
low_anxiety_threat_df
```

```{r ooo_plot, OOO Plot 1.2 Anxiety, echo=FALSE}

#high anxiety
ggplot(data = high_anxiety_threat_df, mapping = aes(x = chosenThreatStatus, y = percentage_chosenThreatStatus, fill = chosenThreatStatus)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1) +
  ggtitle("High Trait Anxiety, Odd One Out Inaccurate Choices") +
  labs (x = "Chosen Threat Status", y = "Percentage")

#fixing some error that pops up with moderate anxiety "must request at least one colour from a hue palette"
my_palette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

#moderate anxiety
ggplot(data = moderate_anxiety_threat_df, mapping = aes(x = chosenThreatStatus, y = percentage_chosenThreatStatus, fill = chosenThreatStatus)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1) +
  ggtitle('Moderate Trait Anxiety, Odd One Out Inaccurate Choices') +
  labs(x = "Chosen Threat Status", y = "Percentage") +
  scale_fill_manual(values = my_palette)

#low anxiety
ggplot(data = low_anxiety_threat_df, mapping = aes(x = chosenThreatStatus, y = percentage_chosenThreatStatus, fill = chosenThreatStatus)) +
  geom_boxplot(alpha = 0.5) +
  geom_jitter(width=0.1) +
  ggtitle ('Low Trait Anxiety, Odd One Out Inaccurate Choices') +
  labs(x = "Chosen Threat Status", y = "Percentage")
```




```{r data manipulation, OOO 2.1 Anxiety}
STAI_subject_acc_ooo_df <- merge(ooo_df, df_pilot1_STAI_simple, by = "subject", all = TRUE)
STAI_subject_acc_ooo_df

STAI_subject_acc_ooo_df <- STAI_subject_acc_ooo_df %>%
  group_by(subject, chosenThreatStatus, anxiety_level) %>%
  summarize(mean_acc = mean(acc))
STAI_subject_acc_ooo_df

#high anxiety data frame, ooo
high_anxiety_ooo_df <- STAI_subject_acc_ooo_df %>%
  filter(anxiety_level == 'high trait anxiety')
high_anxiety_ooo_df

#moderate anxiety data frame, ooo
moderate_anxiety_ooo_df <- STAI_subject_acc_ooo_df %>%
  filter(anxiety_level == 'moderate trait anxiety')
moderate_anxiety_ooo_df

#low anxiety data frame, ooo
low_anxiety_ooo_df <- STAI_subject_acc_ooo_df %>%
  filter(anxiety_level == 'low trait anxiety')
low_anxiety_ooo_df

```

```{r OOO Plot 2.1 Anxiety, echo=FALSE}
ggplot(high_anxiety_ooo_df, aes(x = chosenThreatStatus, y = mean_acc, fill=chosenThreatStatus)) +
  geom_boxplot(alpha=0.5) +
  geom_jitter(width=0.1) +
  ggtitle('High Trait Anxiety, Mean Accuracy in Odd One Out Task by Chosen Threat Status')+
  labs(x= "Chosen Threat Status", y = "Mean Accuracy")

ggplot(moderate_anxiety_ooo_df, aes(x = chosenThreatStatus, y = mean_acc, fill=chosenThreatStatus)) +
  geom_boxplot(alpha=0.5) +
  geom_jitter(width=0.1) +
  ggtitle('Moderate Trait Anxiety, Mean Accuracy in Odd One Out Task by Chosen Threat Status')+
  labs (x = "Chosen Threat Status", y = "Mean Accuracy")

ggplot(low_anxiety_ooo_df, aes(x = chosenThreatStatus, y = mean_acc, fill=chosenThreatStatus)) +
  geom_boxplot(alpha=0.5) +
  geom_jitter(width=0.1) +
  ggtitle('Low Trait Anxiety, Mean Accuracy in Odd One Out Task by Chosen Threat Status') +
  labs (x = "Chosen Threat Status", y = "Mean Accuracy")
```





